# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
# from ubuntu, may be redundant
shopt -s checkwinsize

# the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
# from ubuntu, not enabled by default
shopt -s globstar

# If this is an xterm set the title to user@host:dir
# from ubuntu, may be redundant
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
# from ubuntu, modified for other OSes, may be redundant
if [ -x "$(which dircolors)" ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
# from ubuntu, may be redundant
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# enable programmable completion features
# from ubuntu, may be redundant
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    echo -n "loading completion... "
    . /etc/bash_completion
    echo "done"
fi


# End ubuntu defaults


# set color prompt
function color {
    if [ "$1" == "1" ]; then
        z="32"
    elif [ "$1" == "2" ]; then
        z="34"
    else
        z=""
    fi
    echo -n '\[\033['"$z"'m\]'

}
PS1="`color 1`\u@\h`color`:`color 2`\w`color`\$ "
unset c


# see also http://mywiki.wooledge.org/BashFAQ/088
unset HISTSIZE
unset HISTFILESIZE
export HISTTIMEFORMAT=" "
