filetype plugin on
filetype indent on
set guioptions-=m " turn off menu bar
set guioptions-=T " turn off toolbar

" pythony tabs
set autoindent smarttab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set backspace=indent,eol,start " defaults to eol,start iirc

" line numbers
set number

" highlight the current line on the current window with underline
autocmd VimEnter * set cul
augroup BgHighlight
    autocmd!
    autocmd WinEnter * set cul
    autocmd WinLeave * set nocul
augroup END

set history=50000 " increase history 'cause I like lots of it

set hlsearch " I like to see my searches

"set foldmethod=indent   "fold based on indent
set foldmethod=indent
set foldnestmax=10      "deepest fold is 10 levels

" 
highlight Folded ctermbg=none ctermfg=DarkBlue cterm=none
set foldcolumn=0 " no fold indicator column next to line numbers
set foldtext=MyFoldText() " fancy fold text
function! MyFoldText()
    let line = v:foldstart
    let indent = indent(line)
    let indenttext = repeat(" ", indent) " take indent into account when displaying foldtext
    let text = indenttext . foldtext() 
    return text
endfunction
set fillchars="fold:"

if has("syntax")
  syntax enable
endif

set nowrap

" I like being able to scroll with the mouse, since it's so close-by
" on my laptop keyboard anyway
set mouse=a 

" f2 to toggle paste mode
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

" color the normally confusing paren-highlight to a color that isn't too
" horribly prominent so I can actually tell what's what
highlight MatchParen cterm=NONE ctermbg=black ctermfg=darkblue

" for some reason after loading ~/.vimrc with `source ~/.vimrc` inside vim,
" everything gets highlighted. this works around that.
noh

hi Search cterm=NONE ctermfg=grey ctermbg=darkblue
hi Visual cterm=NONE ctermfg=black ctermbg=darkyellow
